#!/bin/bash

# for i in 1 2 3 4 5 6 7 8 9;
# do
#         for j in 'HypersphericalProbit';
#         do
#                 echo -e "#!/bin/bash\n#SBATCH --partition=ccm -N1 --job-name='$i$j'\nsource /mnt/home/mjhajaria/miniconda3/etc/profile.d/conda.sh\nconda activate stan\n cd /mnt/home/mjhajaria/transforms\n python3 utils/script-simplex.py --parameters=$i --transform='$j'">>/mnt/home/mjhajaria/transforms/utils/slurm/scripts/$i$j.slurm
#                 sbatch /mnt/home/mjhajaria/transforms/utils/slurm/scripts/$i$j.slurm
#         done
# done

# for i in 3 6 9;
# do
#         for j in 'ProbitProduct' 'HypersphericalAngular';
#         do
#                 echo -e "#!/bin/bash\n#SBATCH --partition=ccm -N1 --job-name='$i$j'\nsource /mnt/home/mjhajaria/miniconda3/etc/profile.d/conda.sh\nconda activate stan\n cd /mnt/home/mjhajaria/transforms\n python3 utils/script-simplex.py --parameters=$i --transform='$j' --inits=0.1">>/mnt/home/mjhajaria/transforms/utils/slurm/scripts/$i$j.slurm
#                 sbatch /mnt/home/mjhajaria/transforms/utils/slurm/scripts/$i$j.slurm
#         done
# done

#9probitproduct not done

for i in 1 2 4 5 7 8 ;
do
        for j in 'ProbitProduct';
        do
                echo -e "#!/bin/bash\n#SBATCH --partition=ccm -N1 --job-name='$i$j'\nsource /mnt/home/mjhajaria/miniconda3/etc/profile.d/conda.sh\nconda activate stan\n cd /mnt/home/mjhajaria/transforms\n python3 utils/script-simplex.py --parameters=$i --transform='$j'">>/mnt/home/mjhajaria/transforms/utils/slurm/scripts/$i$j.slurm
                sbatch /mnt/home/mjhajaria/transforms/utils/slurm/scripts/$i$j.slurm
        done
done